name: Weekly Documentation Audit
on:
  schedule:
    - cron: "0 3 * * 1"
jobs:
  doc-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install pnpm
        run: npm i -g pnpm@latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate TypeDoc JSON
        run: pnpm typedoc --json docs.json
      - name: Run Audit Script
        run: node ./scripts/audit-docs.js
